### ISSUE TITLE
problem.md or Readme.md?

### ISSUE THREAD

**Issue by ghost** [Sequoia/clijs#16]
Some exercises define the problem using `problem.md` and other use `Readme.md`

Let's get consistent  !!:exclamation:!

:ram: :sheep: :sheep: :ram: :ram: :sheep: :ram:

**Comment by Sequoia** [comment]
hmmm... I guess I could try

``` sh
$ find . -name problem.md | sed -e "p;s/problem/Readme/" | xargs -n2 git mv
$ ack problem.md -l | xargs sed -e 's/problem.md/Readme.md/' -i ''
```

I'll see if that works. :wink:

**Comment by ghost** [comment]
And I thought _I_ liked making things complicated...

``` sh
$ find . -name problem.md | rename -s problem readme
$ git add -A
```

**Comment by Sequoia** [comment]
Rename wasn't working for some reason :p

**Comment by Sequoia** [comment]
```
/tmp ⌚ 13:53:11
$ rename
zsh: command not found: rename

/tmp ⌚ 13:53:14
$ which rename
rename not found
```

:disappointed:
