### ISSUE TITLE
Pipes

### ISSUE THREAD

**Issue by Sequoia** [Sequoia/clijs#6]
How to accept an incoming stream, specifically output of another program piped into the user's program. Goal is to have >1 incoming chunk while _keeping it as simple as possible_.
## also

recommend/link to `stream-adventure` in the docs for people who want to learn more about streams.

**Comment by ghost** [comment]
@Sequoia follow up on this? Are we done with this one?

**Comment by Sequoia** [comment]
Yeah sry didn't have time to try it this weekend! Will do presently :)

**Comment by ghost** [comment]
Do you think that we should mix this with arguments to support something like this?

```
cat macbeth.txt | solution.js --word=thou
```

Multiple tests could assert that the program displays the correct lines for a variety of `--word` arguments

**Comment by Sequoia** [comment]
hmmmmmm..... my knee jerk reaction is KISS & leave that out, as I outline [here](https://github.com/Sequoia/clijs/issues/9#issuecomment-88235137), but in that case the proposal was introducing `hapi` whereas in this it's building on/reinforcing an existing concept.

Yeah I say "do it" :+1: :ok_hand: :smiley_cat:

**Comment by ghost** [comment]
- [x] Add `--word` parameter
- [x] Update exercise [`verify`](https://github.com/Sequoia/clijs/blob/master/exercises/using_pipes/index.js#L16-L24)
- [x] Update exercise [`problem.md`](https://github.com/Sequoia/clijs/blob/master/exercises/using_pipes/problem.md) file
- [x] Update [`boilerplate.js`](https://github.com/Sequoia/clijs/blob/master/exercises/using_pipes/boilerplate.js#L1-L3) to suggest using `minimist`

**Comment by Sequoia** [comment]
all done?!

**Comment by Sequoia** [comment]
I'll review when I get a chance sry for delay!

**Comment by Sequoia** [comment]
wrt boilerplate.js I think it might be better to move some of that into the `Example` section of the Readme: learners should have to type at least some of that in themselves for the purposes of rote.  Also I'm trying to keep English strings out of the boilerplate/solution as much as possible to ease eventual i18n. :pray:

**Comment by Sequoia** [comment]
## Notes
- Add note about npm install minimist
- Add note about toString on buffers
  - heh actually `console.log('x' + ...read())` casts buffer to str but `console.log('x', ...read())` (i.e. 2 args for console.log does _not_. The latter is in the boilerplate
  - `console.log("reading:" + process.stdin.read().toString());` does not work because readable is emitted with a `null` on end of input it seems :/
  
  ``` javascript
  process.stdin.on('readable', function() {
    var buffer = process.stdin.read();
    if(buffer === null) { return; }
    console.log("reading:" + buffer);
  });
  ```
  
  ^ This basically work
- boilerplate (console.log in `on('readable'),`) may actually lead the learner **away** from the solution-- it seems intuitive that `cl`ing should happen on readable but really it should (probably) happen on `end`
- **note what `clijs run` does** I think it should actually set up the env like it will be set up for `verify`, i.e. pipe data in & feed it a switch
- link to buffer docs?
- link to regexp.test
- note about splitting on lines
- ~~link to process.stdin or whatever docs~~
- Note that we are keeping this simple & there’s a full lesson `stream-adventure` if they want to learn more about this exciting topic
- "Append to `results` string then operate on it `on('end')`" pattern is  canonical but not necessarily obvious. I suggest adding note/example that highlights this technique
- I may shorten intro if that's alright

## My Impression

I'd probably say that this lesson is "too hard" as it currently stands.  It took
me a minute to figure it out and I'm reasonably good at this stuff. I want to
carefully avoid (as much as possible) learners getting "stuck", and I think this
lesson would get people a lot of people stuck.

## Proposal
1. Focus-group it some on IRC
2. Add hints
3. Find ways to make this one "easier"

**Comment by Sequoia** [comment]
Will create new ticket for revisions. Initial version is :+1: done.
